### PR TITLE
Android ald

### PR DESCRIPTION
**Pull request by aldesilv**
viewDonationDetails, addDonation,
freshness, login textfields, donations data struct , valid donations

### CODE REVIEW

**Comment by addisonmartin** [comment]
It seems like the freshness animation won't stay on the screen very long. I wonder if we should increase it to minutes?

**Comment by addisonmartin** [comment]
In Login, you have a code smells associated to duplicated code. There's a lot of repeated create Alert DIalogs and I wonder if it would be better to move them into a method.

**Comment by aldesilv** [comment]
can change from seconds to minutes, could use a different widget than a timer/ a new custom widget

**Comment by addisonmartin** [comment]
Finally, I think you should add a method in Donation that checks if its valid. Name and pickup details are mandatory (ie length not 0), but most of the filters and image are optional. Freshness value is required.

**Pull request merged**
