### PR TITLE
Finished fixing bugs on FILTERS. CODE REVIEW ASSGN

### PR DESCRIPTION
**Pull request by addisonmartin**
@aldesilv can you please code review this today? To see the full code for filters, you'll have to go into master branch. I accidentally merged in filters to master when I was finishing up stuff for the sprint review today. This is only a bug fix commit, but please discuss full filters feature!

### CODE REVIEW

**Comment by aldesilv** [comment]
It looks good, how are you able to access 'sharedPreferences stored' to get the changes in  'addFilters' to  'viewDonationList'? 
also, addFilters says that you are only able to get it to work with one filter at a time, have you already figured out why?

**Comment by addisonmartin** [comment]
SharedPreferences is a flutter plugin that allows you to store SMALL amounts of data on the disk. This way you can pass filters from the filter view back to the list view, but also your filters persist through the lifetime of using the app. Currently they're reset when you launch the app, but that could be disabled.

**Comment by addisonmartin** [comment]
I have not been able to figure out why multiple filters aren't working! I suspect it has something to do with the way I build the new filtered list. If something is gluten free and not dairy free, and both gluten free and dairy free are selected filters, then it would still appear (until I only allowed one filter). The solution, I think, involves how I combine multiple filters and decide the eligibility of the item.

**Comment by aldesilv** [comment]
ok, i understand what you mean now, looks like we'd need to change how we get the items in the viewDonationList.

**Pull request merged**
